### ISSUE TITLE
RssFormatter is not rendering the Atom namespace at the top of the feed

### ISSUE THREAD

**Issue by skonsoft** [eko/FeedBundle#47] opened 2015-04-09 23:14 UTC
According to w3c validator, the feed should contain the atom namespace.
here is the spec: http://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html

So when i tried to validate my RSS generated Feed, it was validated because the Atom namespace is messing.

this the current rendering: 
`<rss version="2.0">`

Instead of this, we need to get: 
`<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">`

So, jusr add in the RssFormatter:
`$root->setAttribute('xmlns:atom', "http://www.w3.org/2005/Atom");`

and the feed channel section, add:
`<atom:link href="http://example.com/feed.xml" rel="self" type="application/rss+xml" />`

here we need to put the href of the feed as config variable.

Thank you !

**Comment by eko** [comment] 2015-04-11 08:24
Hi @skonsoft,

This occurs because you are using the `rss` formatter (`$feed->render('rss');`) instead of the `atom` formatter which will use the Atom XML namespace to validate your feed.

However, you were right about the `link` attribute as there is a recommandation that tells to have a `rel` attribute on `link` node. I've added it.

I close this issue as I think the problem is solved. Do not hesitate to reopen if you think it is still relevant.

Thank you.

**Closed by eko** 2015-04-11 08:24 UTC
